name: IP Ready Scans
on: [push]
 
jobs:
  checkmarx_scan:
    if: startsWith(github.ref, 'refs/heads/sast/')
    name: SAST Scan
    uses: CognizantCodeHub/IPReady_workflows/.github/workflows/checkmarx_scan.yml@Rel-1.0
    with:
      ProjectName: ${{ github.event.repository.name }}
      location_path_exclude: 'build_scripts/**,**/tests/**'
    secrets: inherit
    
  blackduck_scan: 
    name: Blackduck Scan
    if: startsWith(github.ref, 'refs/heads/oss/')
    runs-on: codebuild-cdhb-ubuntu-cdbuild-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: Blackduck Scan  
      uses: CognizantCodeHub/IPReady_workflows/blackduck/generic@Include_detector
      with:
        ProjectName: ${{ github.event.repository.name }}
        SYNOPSIS_URL: ${{ secrets.SYNOPSIS_URL }}
        BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
        BLACKDUCK_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
        version: 'ver.0.6.0'
        include_detector_types: 'PIP'
        bdh_accuracy_required: 'NONE' 
