---
name: Test

permissions:
  contents: read

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]
    branches:
      - main
jobs:
  test:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')
    # 1.0.12
    uses: cognizant-ai-lab/build-common/.github/workflows/_python-quality-gate.yml@3f4cdab31b6ac10382c99452b720eb0b8b2dab8f
    with:
      python-version: '3.12'
      test-python-versions: '["3.12", "3.13", "3.14"]'
      lint-toolchain: 'legacy'
      pylint-command: 'build_scripts/run_pylint.sh'
      run-shellcheck: true
      pytest-markers: 'not integration'
      pytest-extra-args: '--timer-top-n 10 --cov-config=.coveragerc --cov'
      check-readme-pypi: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
